# Generated by Django 4.2.29 on 2026-03-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="类别名称")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="expenses.expensecategory",
                        verbose_name="父类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "支出类别",
                "verbose_name_plural": "支出类别",
                "db_table": "expense_category",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="描述"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.expensecategory",
                        verbose_name="类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "开支",
                "verbose_name_plural": "开支",
                "db_table": "expense",
                "ordering": ["-date"],
            },
        ),
    ]
